version: '3'

services:
  flask-app:
    build: ./
    ports:
      - 8080:8080
    environment:
      - MYSQL_HOST=mydb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=color_db
    depends_on:
      - db
    networks:
            -  db-network

  db:
    container_name: mydb
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=color_db
    networks:
            -  db-network

networks:
    db-network:
        name:  db-network